import { Grade, Subject, Textbook, Unit, Correction } from "./types";

export const initialGrades: Grade[] = [
  {
    "id": "grade-9",
    "name": "Grade 9",
    "slug": "grade-9",
    "orderIndex": 1
  },
  {
    "id": "grade-10",
    "name": "Grade 10",
    "slug": "grade-10",
    "orderIndex": 2
  },
  {
    "id": "grade-11",
    "name": "Grade 11",
    "slug": "grade-11",
    "orderIndex": 3
  },
  {
    "id": "grade-12",
    "name": "Grade 12",
    "slug": "grade-12",
    "orderIndex": 4
  }
];

export const initialSubjects: Subject[] = [
  {
    "id": "biology",
    "name": "Biology",
    "slug": "biology",
    "description": "Living organisms, cytology, physiology, genetics, ecology, and biotechnology.",
    "icon": "Dna"
  },
  {
    "id": "chemistry",
    "name": "Chemistry",
    "slug": "chemistry",
    "description": "Atomic theory, chemical bonding, organic compounds, and industrial chemistry.",
    "icon": "FlaskConical"
  },
  {
    "id": "physics",
    "name": "Physics",
    "slug": "physics",
    "description": "Mechanics, thermodynamics, wave optics, electromagnetism, and modern physics.",
    "icon": "Atom"
  },
  {
    "id": "mathematics",
    "name": "Mathematics",
    "slug": "mathematics",
    "description": "Algebra, calculus, geometry, trigonometry, and statistical methods.",
    "icon": "Binary"
  },
  {
    "id": "it",
    "name": "Information Technology",
    "slug": "it",
    "description": "Computing systems, databases, network architecture, and programming fundamentals.",
    "icon": "Cpu"
  },
  {
    "id": "english",
    "name": "English",
    "slug": "english",
    "description": "Language skills, reading comprehension, grammar, and academic writing.",
    "icon": "BookOpen"
  },
  {
    "id": "geography",
    "name": "Geography",
    "slug": "geography",
    "description": "Physical landscapes, climate systems, population dynamics, and economic geography of Ethiopia.",
    "icon": "Globe"
  },
  {
    "id": "history",
    "name": "History",
    "slug": "history",
    "description": "Ethiopian history, African kingdoms, colonialism, and contemporary international affairs.",
    "icon": "Landmark"
  },
  {
    "id": "economics",
    "name": "Economics",
    "slug": "economics",
    "description": "Microeconomics, macroeconomic stability, fiscal policy, and national development.",
    "icon": "TrendingUp"
  }
];

export const initialTextbooks: Textbook[] = [
  {
    "id": "g11-biology",
    "title": "Ethiopian New Curriculum Grade 11 Biology Student Textbook",
    "gradeId": "grade-11",
    "subjectId": "biology",
    "curriculum": "Ethiopian New Curriculum (2023/2024)",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Federal Democratic Republic of Ethiopia",
    "status": "Active",
    "description": "Standard national textbook for Grade 11 Biology under the revised Ethiopian curriculum.",
    "coverImage": "/images/hero-floating.jpg"
  },
  {
    "id": "g11-chemistry",
    "title": "Ethiopian New Curriculum Grade 11 Chemistry Student Textbook",
    "gradeId": "grade-11",
    "subjectId": "chemistry",
    "curriculum": "Ethiopian New Curriculum",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Federal Democratic Republic of Ethiopia",
    "status": "Under Systematic Review",
    "description": "Grade 11 Chemistry textbook. Currently queued for error documentation."
  },
  {
    "id": "g11-physics",
    "title": "Ethiopian New Curriculum Grade 11 Physics Student Textbook",
    "gradeId": "grade-11",
    "subjectId": "physics",
    "curriculum": "Ethiopian New Curriculum",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Federal Democratic Republic of Ethiopia",
    "status": "Under Systematic Review",
    "description": "Grade 11 Physics textbook. Systematic review currently scheduled."
  },
  {
    "id": "g11-mathematics",
    "title": "Ethiopian New Curriculum Grade 11 Mathematics Student Textbook",
    "gradeId": "grade-11",
    "subjectId": "mathematics",
    "curriculum": "Ethiopian New Curriculum",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Federal Democratic Republic of Ethiopia",
    "status": "Under Systematic Review",
    "description": "Grade 11 Mathematics textbook under national curriculum."
  },
  {
    "id": "g10-biology",
    "title": "Ethiopian New Curriculum Grade 10 Biology Student Textbook",
    "gradeId": "grade-10",
    "subjectId": "biology",
    "curriculum": "Ethiopian New Curriculum",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Ethiopia",
    "status": "Scheduled",
    "description": "Grade 10 Biology textbook. Scheduled for review."
  },
  {
    "id": "g9-biology",
    "title": "Ethiopian New Curriculum Grade 9 Biology Student Textbook",
    "gradeId": "grade-9",
    "subjectId": "biology",
    "curriculum": "Ethiopian New Curriculum",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Ethiopia",
    "status": "Scheduled",
    "description": "Grade 9 Biology textbook. Scheduled for review."
  },
  {
    "id": "g12-biology",
    "title": "Ethiopian New Curriculum Grade 12 Biology Student Textbook",
    "gradeId": "grade-12",
    "subjectId": "biology",
    "curriculum": "Ethiopian New Curriculum",
    "language": "English",
    "edition": "First Edition",
    "publisher": "Ministry of Education, Ethiopia",
    "status": "Scheduled",
    "description": "Grade 12 Biology textbook. Scheduled for review."
  }
];

export const initialUnits: Unit[] = [
  {
    "id": "g11-bio-unit-1",
    "textbookId": "g11-biology",
    "unitNumber": 1,
    "title": "Biology and Technology",
    "slug": "unit-1",
    "description": "Examines biomimicry, diagnostic technology, medical tools, and the reciprocal relationship between biological science and technology.",
    "pageRange": "Pages 1\u201320",
    "reviewStatus": "Research Completed",
    "pdfUrl": "/reports/Grade-11-Biology-Unit-1-Correction-Report.pdf",
    "isPublished": true
  },
  {
    "id": "g11-bio-unit-2",
    "textbookId": "g11-biology",
    "unitNumber": 2,
    "title": "Animals",
    "slug": "unit-2",
    "description": "Systematic study of invertebrates and vertebrates, animal behavior, anatomical structures, and physiological systems.",
    "pageRange": "Pages 21\u201368",
    "reviewStatus": "Under Review",
    "pdfUrl": "/reports/Grade-11-Biology-Unit-2-Correction-Report.pdf",
    "isPublished": false
  },
  {
    "id": "g11-bio-unit-3",
    "textbookId": "g11-biology",
    "unitNumber": 3,
    "title": "Enzymes",
    "slug": "unit-3",
    "description": "Enzyme classification, kinetics, active site theory, cofactors, inhibitors, and cellular metabolism.",
    "pageRange": "Pages 69\u2013102",
    "reviewStatus": "Under Review",
    "isPublished": false
  },
  {
    "id": "g11-bio-unit-4",
    "textbookId": "g11-biology",
    "unitNumber": 4,
    "title": "Genetics",
    "slug": "unit-4",
    "description": "Mendelian genetics, chromosome theory, non-Mendelian inheritance patterns, genetic mutations, and pedigree analysis.",
    "pageRange": "Pages 103\u2013156",
    "reviewStatus": "Scheduled",
    "isPublished": false
  },
  {
    "id": "g11-bio-unit-5",
    "textbookId": "g11-biology",
    "unitNumber": 5,
    "title": "The Human Body Systems",
    "slug": "unit-5",
    "description": "Cardiovascular, pulmonary, nervous, digestive, and hormonal coordination in humans.",
    "pageRange": "Pages 157\u2013220",
    "reviewStatus": "Scheduled",
    "isPublished": false
  }
];

export const initialCorrections: Correction[] = [
  {
    "id": "c-p2-01",
    "refCode": "P2-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 2,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Redundant conjunction and incorrect preposition",
    "originalText": "Organisms have well-adapted structures and that make them survive on their immediate environment.",
    "issue": "Redundant \"and\" before \"that\" breaks the sentence; wrong preposition (\"on\" instead of \"in\").",
    "suggestedCorrection": "Organisms have well-adapted structures that help them survive in their immediate environment.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:00:00.000Z",
    "updatedAt": "2024-09-01T10:00:00.000Z"
  },
  {
    "id": "c-p2-02",
    "refCode": "P2-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 2,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Missing preposition after gerund",
    "originalText": "The better their understanding the diverse nature of biological materials, the better their ability to develop technologies.",
    "issue": "Missing \"of\" after \"understanding.\"",
    "suggestedCorrection": "The better their understanding of the diverse nature of biological materials, the better their ability to develop technologies.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:05:00.000Z",
    "updatedAt": "2024-09-01T10:05:00.000Z"
  },
  {
    "id": "c-p2-03",
    "refCode": "P2-03",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 2,
    "category": "Conceptual/Definitional",
    "severity": "Moderate",
    "title": "Definition contradicts its own illustrative examples",
    "originalText": "Nature is the physical, natural and material world of life that exists without human intervention. It includes landscape sceneries, water and forest ecosystems, weather, organisms, geology, celestial bodies and inanimate objects, etc.",
    "issue": "Nature is defined as the \"world of life,\" but the examples that follow are mostly non-living (landscapes, water, weather, geology, celestial bodies, inanimate objects) with \"organisms\" as just one item among many. The definition doesn't match its own examples.",
    "suggestedCorrection": "Nature is the physical and material world that exists without human intervention. (drop \"of life,\" or explicitly note it covers both living and non-living things)",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:10:00.000Z",
    "updatedAt": "2024-09-01T10:10:00.000Z"
  },
  {
    "id": "c-p2-04",
    "refCode": "P2-04",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 2,
    "category": "Word Choice",
    "severity": "Minor",
    "title": "Improper adjective applied to biological structures",
    "originalText": "Nature provides us with doable structures and forms...",
    "issue": "\"Doable\" describes tasks, not structures/forms.",
    "suggestedCorrection": "Nature provides us with usable structures and forms...",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:15:00.000Z",
    "updatedAt": "2024-09-01T10:15:00.000Z"
  },
  {
    "id": "c-p2-05",
    "refCode": "P2-05",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 2,
    "category": "Word Choice",
    "severity": "Minor",
    "title": "Idiom mismatch in engineering context",
    "originalText": "...they can sketch the biological structures, design functional mechanisms and tune into more efficient technologies...",
    "issue": "\"Tune into\" doesn't fit here.",
    "suggestedCorrection": "...design functional mechanisms, and turn them into more efficient technologies...",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:20:00.000Z",
    "updatedAt": "2024-09-01T10:20:00.000Z"
  },
  {
    "id": "c-p3-01",
    "refCode": "P3-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 3,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Faulty sentence structure and verb tense",
    "originalText": "The design and adaptation of many technologies we utilize today imitated natural working systems.",
    "issue": "Broken sentence structure/verb tense.",
    "suggestedCorrection": "Many of the technologies we use today were designed and adapted by imitating natural working systems.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:25:00.000Z",
    "updatedAt": "2024-09-01T10:25:00.000Z"
  },
  {
    "id": "c-p3-02",
    "refCode": "P3-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 3,
    "category": "Word Choice",
    "severity": "Minor",
    "title": "Voice error, missing article, and non-standard temporal idiom",
    "originalText": "Many technologies have been imitating birds, bats, termites, spiders, bees, ants and parts of human body since timeless.",
    "issue": "Wrong voice (technologies don't imitate \u2014 they are imitations); missing article before \"human body\"; \"since timeless\" is not standard English.",
    "suggestedCorrection": "Many technologies have imitated birds, bats, termites, spiders, bees, ants, and parts of the human body since time immemorial.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:30:00.000Z",
    "updatedAt": "2024-09-01T10:30:00.000Z"
  },
  {
    "id": "c-p3-03",
    "refCode": "P3-03",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 3,
    "category": "Factual Error",
    "severity": "Moderate",
    "title": "Misspelled landmark building name and cross-figure inconsistency",
    "originalText": "An example is The East gate Center in Harare (Figure 1.2).",
    "issue": "The building's actual name is the Eastgate Centre (confirmed via source-checking), not \"East gate Center.\" Figure 1.2's own caption on the next page calls it \"East Gate Building\" \u2014 a third, different name for the same building. All three should match.",
    "suggestedCorrection": "An example is the Eastgate Centre in Harare (Figure 1.2).",
    "relatedRefCodes": [
      "P4-01"
    ],
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:35:00.000Z",
    "updatedAt": "2024-09-01T10:35:00.000Z"
  },
  {
    "id": "c-p4-01",
    "refCode": "P4-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Consistency",
    "severity": "Minor",
    "title": "Caption naming mismatch for Eastgate Centre",
    "originalText": "Figure 1.2 caption \u2014 \"Mound inspired architecture for the East Gate Building\"",
    "issue": "Third variant of the same building's name in as many mentions (pairs with P3-03).",
    "suggestedCorrection": "Mound-inspired architecture for the Eastgate Centre",
    "relatedRefCodes": [
      "P3-03"
    ],
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:40:00.000Z",
    "updatedAt": "2024-09-01T10:40:00.000Z"
  },
  {
    "id": "c-p4-02",
    "refCode": "P4-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Punctuation",
    "severity": "Minor",
    "title": "Missing terminal period at end of list item",
    "originalText": "...by imitating the wings of birds and bats (end of item 4)",
    "issue": "Missing terminal period before item 5 begins.",
    "suggestedCorrection": "Add a period at the end of the sentence.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:45:00.000Z",
    "updatedAt": "2024-09-01T10:45:00.000Z"
  },
  {
    "id": "c-p4-03",
    "refCode": "P4-03",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Awkward unidiomatic phrasing in optical technology statement",
    "originalText": "Engineers imitating human eyes made the technology of photograph camera.",
    "issue": "Awkward, non-standard phrasing.",
    "suggestedCorrection": "Engineers imitating the human eye developed camera technology.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:50:00.000Z",
    "updatedAt": "2024-09-01T10:50:00.000Z"
  },
  {
    "id": "c-p4-04",
    "refCode": "P4-04",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Missing pluralization and article in bio-robotics statement",
    "originalText": "The movement of bio-robots was designed from the movement of kangaroo.",
    "issue": "Missing article/plural.",
    "suggestedCorrection": "The movement of bio-robots was designed from the movement of kangaroos.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T10:55:00.000Z",
    "updatedAt": "2024-09-01T10:55:00.000Z"
  },
  {
    "id": "c-p4-05",
    "refCode": "P4-05",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Consistency",
    "severity": "Minor",
    "title": "Article omission and internal discrepancy with figure caption",
    "originalText": "Injection needle technology was copied from mosquito proboscis (Figure 1.3).",
    "issue": "Missing article \u2014 and Figure 1.3's own caption correctly says \"a mosquito's proboscis,\" so the list item doesn't match its own figure.",
    "suggestedCorrection": "Injection needle technology was copied from a mosquito's proboscis (Figure 1.3).",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:00:00.000Z",
    "updatedAt": "2024-09-01T11:00:00.000Z"
  },
  {
    "id": "c-p4-06",
    "refCode": "P4-06",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Scientific Terminology",
    "severity": "Moderate",
    "title": "Incorrect technical phrasing 'spin silks'",
    "originalText": "Synthetic bulletproof vests are imitations of the spin silks of spiders.",
    "issue": "\"Spin silks\" isn't correct terminology \u2014 spiders spin silk; the material is \"spider silk.\"",
    "suggestedCorrection": "Synthetic bulletproof vests are imitations of spider silk.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:05:00.000Z",
    "updatedAt": "2024-09-01T11:05:00.000Z"
  },
  {
    "id": "c-p4-07",
    "refCode": "P4-07",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 4,
    "category": "Flag for expert verification",
    "severity": "Moderate",
    "title": "Mollusk shell incorrectly labeled as 'exoskeleton'",
    "originalText": "Ceramics are an imitation of the nature of crack-resistant shellfish exoskeleton.",
    "issue": "Mollusk shells (e.g., abalone/nacre) are usually called shells, not \"exoskeletons\" \u2014 that term is standard for arthropods (crabs, insects). Worth a biology teacher's call on whether to keep or correct.",
    "suggestedCorrection": "Ceramics are an imitation of the crack-resistant shell structure of shellfish (nacre).",
    "specialNotes": "Flag for expert review / teacher review regarding standard terminology.",
    "researchStatus": "Needs Expert Review",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:10:00.000Z",
    "updatedAt": "2024-09-01T11:10:00.000Z"
  },
  {
    "id": "c-p5-01",
    "refCode": "P5-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 5,
    "category": "Consistency",
    "severity": "Minor",
    "title": "Caption article omission and number mismatch with text body",
    "originalText": "Figure 1.4 caption \u2014 \"Robotic arms imitated from elephant trunk\"",
    "issue": "Missing article; also switches to plural \"arms\" when the body list (item 12) correctly says singular \"a robotic arm...an elephant trunk.\"",
    "suggestedCorrection": "Robotic arm imitated from an elephant's trunk",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:15:00.000Z",
    "updatedAt": "2024-09-01T11:15:00.000Z"
  },
  {
    "id": "c-p5-02",
    "refCode": "P5-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 5,
    "category": "Typo",
    "severity": "Minor",
    "title": "Stray apostrophe following question mark",
    "originalText": "How closely does your model hand match a natural human hand?'",
    "issue": "Stray apostrophe after the question mark.",
    "suggestedCorrection": "How closely does your model hand match a natural human hand?",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:20:00.000Z",
    "updatedAt": "2024-09-01T11:20:00.000Z"
  },
  {
    "id": "c-p6-01",
    "refCode": "P6-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 6,
    "category": "Consistency",
    "severity": "Minor",
    "title": "Margin question duplicate variants ('coupling' vs 'blend')",
    "originalText": "Margin questions: \"What does the coupling of biology and technology form?\" and \"What does the blend of biology and technology form?\"",
    "issue": "The extracted text contains two differently worded versions of what appears to be the same margin question. Please verify against the original layout \u2014 if both are genuinely printed, they should be unified (the body paragraph itself uses \"blend,\" so that's the natural choice).",
    "suggestedCorrection": "Unify margin question to: \"What does the blend of biology and technology form?\"",
    "specialNotes": "Flag for layout check against printed textbook.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:25:00.000Z",
    "updatedAt": "2024-09-01T11:25:00.000Z"
  },
  {
    "id": "c-p6-02",
    "refCode": "P6-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 6,
    "category": "Typo",
    "severity": "Minor",
    "title": "Duplicated demonstrative adjective 'the these'",
    "originalText": "Scientists have imitated nature to develop artificial versions of the these biochemical substances.",
    "issue": "Duplicated article/determiner.",
    "suggestedCorrection": "Scientists have imitated nature to develop artificial versions of these biochemical substances.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:30:00.000Z",
    "updatedAt": "2024-09-01T11:30:00.000Z"
  },
  {
    "id": "c-p6-03",
    "refCode": "P6-03",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 6,
    "category": "Consistency",
    "severity": "Moderate",
    "title": "Three conflicting definitions of 'Technology' within a single unit",
    "originalText": "The book defines \"Technology\" three different ways across the unit: as a general use/application of knowledge (Figure, p.1), as knowledge \"for scientific investigations\" (p.6), and as a \"sum of techniques...to accomplish objectives\" (p.17, and echoed in the review-question answer key).",
    "issue": "Conflicting definitions cause student confusion on examinations. Recommend picking one canonical definition and using it consistently, since students will be tested on \"the\" definition.",
    "suggestedCorrection": "Adopt a single canonical definition across all sections: \"Technology is the sum of techniques, skills, methods, and processes used in the production of goods or services or in the accomplishment of objectives.\"",
    "relatedRefCodes": [
      "P17-04"
    ],
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:35:00.000Z",
    "updatedAt": "2024-09-01T11:35:00.000Z"
  },
  {
    "id": "c-p7-01",
    "refCode": "P7-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 7,
    "category": "Consistency",
    "severity": "Minor",
    "title": "Broken grammatical parallelism in inquiry activity list",
    "originalText": "Inquiry activity 1.2, item 2 \u2014 \"A brand new drone design\"",
    "issue": "Breaks the parallel noun-phrase pattern of the rest of the list (\"Hexagonal structures,\" \"Cutting saws,\" etc.).",
    "suggestedCorrection": "Drone design",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:40:00.000Z",
    "updatedAt": "2024-09-01T11:40:00.000Z"
  },
  {
    "id": "c-p8-01",
    "refCode": "P8-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 8,
    "chapterSection": "1.2.2 Uses of technology in biology",
    "category": "Formatting",
    "severity": "Minor",
    "title": "Missing space separator in section heading",
    "originalText": "1.2.2Uses of technology in biology",
    "issue": "Missing space in the section heading.",
    "suggestedCorrection": "1.2.2 Uses of technology in biology",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:45:00.000Z",
    "updatedAt": "2024-09-01T11:45:00.000Z"
  },
  {
    "id": "c-p8-02",
    "refCode": "P8-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 8,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Grammatically broken prepositional phrase 'detailed of information'",
    "originalText": "Biomedical studies deal with providing detailed of information on the chemical components of medicinal plants.",
    "issue": "\"Detailed of information\" is broken.",
    "suggestedCorrection": "Biomedical studies deal with providing detailed information on the chemical components of medicinal plants.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:50:00.000Z",
    "updatedAt": "2024-09-01T11:50:00.000Z"
  },
  {
    "id": "c-p8-03",
    "refCode": "P8-03",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 8,
    "category": "Conceptual/Definitional",
    "severity": "Moderate",
    "title": "Category error defining scientific discipline as 'information'",
    "originalText": "Biogeographical information is the study of the distribution of species along with geographic ecosystems through geological periods.",
    "issue": "This item names a discipline (\"Biogeography\"), but as written it says \"information...is the study of,\" which is a category error \u2014 information isn't a study, a field is. It also breaks the naming pattern used by items 1\u20135 (Biochemical studies, Biomedical studies, Biophysical studies, Environmental studies, Bioinformatics).",
    "suggestedCorrection": "Biogeography is the study of the distribution of species across geographic regions and ecosystems through geological time.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T11:55:00.000Z",
    "updatedAt": "2024-09-01T11:55:00.000Z"
  },
  {
    "id": "c-p8-04",
    "refCode": "P8-04",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 8,
    "category": "Formatting",
    "severity": "Minor",
    "title": "Omitted list number in medical diagnostic devices sequence",
    "originalText": "Numbered list starts \"1. A digital thermometer...\" followed by unnumbered \"A pregnancy urine test is a tool...\" and resumes with \"2. The diabetic blood test\" on p.9.",
    "issue": "The numbered device list starts \"1. A digital thermometer...\" but the next entry, the pregnancy urine test, has no number \u2014 it just starts \"A pregnancy urine test is a tool...\" The list then resumes numbering at \"2. The diabetic blood test\" on p.9. This skips a number in the visible sequence.",
    "suggestedCorrection": "Number the pregnancy test entry \"2.\" and renumber everything after it sequentially through page 10 (diabetic test = 3, HIV test = 4, microscope = 5, CITS = 6, CT scan = 7, PET scan = 8, GPS = 9, body fat calculator = 10).",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T12:00:00.000Z",
    "updatedAt": "2024-09-01T12:00:00.000Z"
  },
  {
    "id": "c-p8-05",
    "refCode": "P8-05",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 8,
    "category": "Grammar",
    "severity": "Minor",
    "title": "Missing preposition 'of' in diagnostic test description",
    "originalText": "...the other line (two lines) confirms the existence pregnancy (Figure 1.7).",
    "issue": "Missing \"of.\" (Sentence is also confusingly structured).",
    "suggestedCorrection": "...confirms the existence of pregnancy (Figure 1.7). (Or clearer rewrite: \"One line indicates a negative result; two lines confirm a positive (pregnant) result.\")",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T12:05:00.000Z",
    "updatedAt": "2024-09-01T12:05:00.000Z"
  },
  {
    "id": "c-p9-01",
    "refCode": "P9-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 9,
    "category": "Typo",
    "severity": "Minor",
    "title": "Typo 'figure tip' and ungrammatical participle clause",
    "originalText": "The diabetic blood test is a tool to measure the level of blood sugar taking sample blood from figure tip (Figure 1.8).",
    "issue": "\"Figure tip\" should be \"fingertip\"; the surrounding phrase is also ungrammatical.",
    "suggestedCorrection": "The diabetic blood test is a tool used to measure blood sugar level by taking a blood sample from the fingertip (Figure 1.8).",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T12:10:00.000Z",
    "updatedAt": "2024-09-01T12:10:00.000Z"
  },
  {
    "id": "c-p9-02",
    "refCode": "P9-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 9,
    "affectedPages": [
      9,
      11,
      13,
      15,
      17,
      19
    ],
    "isRecurring": true,
    "category": "Formatting",
    "severity": "Moderate",
    "title": "Recurring incorrect running header 'UNIT 2: ANIMALS' across Unit 1 pages",
    "originalText": "Running header on odd pages reads: \"UNIT 2: ANIMALS\"",
    "issue": "The header reads \"UNIT 2: ANIMALS\", but this page is still Unit 1: Biology & Technology. This same incorrect running header repeats across pages 9, 11, 13, 15, 17, and 19.",
    "suggestedCorrection": "Change running header to \"UNIT 1: BIOLOGY AND TECHNOLOGY\" across all pages 9, 11, 13, 15, 17, and 19.",
    "specialNotes": "Recurring issue spanning 6 distinct odd-numbered pages in Unit 1.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T12:15:00.000Z",
    "updatedAt": "2024-09-01T12:15:00.000Z"
  },
  {
    "id": "c-p10-01",
    "refCode": "P10-01",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 10,
    "category": "Flag for expert verification",
    "severity": "Critical",
    "title": "Unverified / non-standard imaging modality 'Computer Information Technology Scanning (CITS)'",
    "originalText": "Computer Information Technology Scanning (CITS) is a device used for investigating information on diseases or cancerous areas of the human body.",
    "issue": "Could not find \"Computer Information Technology Scanning\" or the acronym \"CITS\" as a recognized medical imaging technology in standard biomedical literature \u2014 it does not match CT, CAT, MRI, PET, or any standard modality. This may be a garbled or invented term. Recommend a biology/medical reviewer confirm what device was actually intended or cut.",
    "suggestedCorrection": "Confirm intended standard modality with subject-matter expert (e.g., CT/Computed Tomography or cut unverified term).",
    "specialNotes": "Flag for expert verification: medical imaging literature does not corroborate CITS.",
    "researchStatus": "Needs Expert Review",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T12:20:00.000Z",
    "updatedAt": "2024-09-01T12:20:00.000Z"
  },
  {
    "id": "c-p10-02",
    "refCode": "P10-02",
    "unitId": "g11-bio-unit-1",
    "pageNumber": 10,
    "category": "Factual Error",
    "severity": "Critical",
    "title": "Incorrect acronym expansion: 'Geographical Position System'",
    "originalText": "Geographical Position System (GPS) is a device used to collect biogeographical information...",
    "issue": "GPS stands for Global Positioning System, not \"Geographical Position System.\"",
    "suggestedCorrection": "Global Positioning System (GPS) is a device used to collect biogeographical information...",
    "evidence": "GPS is universally defined as Global Positioning System by the international geodesy community and satellite navigation standards.",
    "researchStatus": "Research Completed",
    "publicationStatus": "Published",
    "createdAt": "2024-09-01T12:25:00.000Z",
    "updatedAt": "2024-09-01T12:25:00.000Z"
  }
];
